version: "3.9"
services:
  antmedia:
    build:
      context: .
      target: AMS
      args:
        BranchName: 'master'
        AntMediaServer: 'https://testamsserver.s3.eu-west-3.amazonaws.com/ams.zip'
    container_name: antmedia
    restart: unless-stopped
    entrypoint: /usr/local/antmedia/start.sh
    ports:
      - "5080:5080"
    networks:
      - app

  database:
    image: mysql
    container_name: database
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_HOST_PATH}:/var/lib/mysql
      - ./docker/mysql/init.sql:/data/application/init.sql
    ports:
      - ${DB_HOST_PORT}:3306
    networks:
      - app

  php:
    build:
      context: .
      target: PHP
    container_name: php
    volumes:
      - ./application:/var/www/app
    depends_on:
      - database
      - antmedia
      - composer
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: test
      AMS_URL: http://antmedia:5080
      APP_PORT: ${NGINX_HOST_PORT}
    networks:
      - app


  app:
    build:
      context: .
      target: nginx
    container_name: app
    ports:
      - ${NGINX_HOST_PORT}:80
    links:
      - php
    volumes:
      - ./application:/var/www/app
    depends_on:
      - php
    networks:
      - app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./application:/var/www/app
    working_dir: /var/www/app
    command: composer install  --no-scripts

networks:
  app:
    name: app
    driver: bridge